### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by reportgunner** [theeko74/pdfc#1]
Hello,

I'm using ghostscript 9.25, 64bit version and I was receiving the error in the title until I updated the 'gs' parameter in the list below to 'gswin64c'. I'm not sure how to handle this for all ghostscript versions (32 & 64 bit) and I'm not sure if this was not just my client problem, hence opening an issue and not a pull request.

https://github.com/theeko74/pdfc/blob/2a1811bea97933c0fc439a6f23503189b046e52f/pdf_compressor.py#L50

**Comment by tim-kilian** [comment]
Create a gs.exe link to gswin64c.exe and make sure it is in your PATH 
https://www.howtogeek.com/howto/16226/

**Comment by MetalBearSolid** [comment]
Hi reportgunner,

I'm having the same issue. I'm not sure how to create a gs.exe link to gswin64.exe. Can you tell me how to do it?

Thanks!

**Comment by reportgunner** [comment]
Hello,

I have simply edited the package to call `'gswin64c'` instead of `'gs'` [here](https://github.com/theeko74/pdfc/blob/master/pdf_compressor.py#L50)

    subprocess.call(['gswin64c', '-sDEVICE=pdfwrite', '-dCompatibilityLevel=1.4',
