### ISSUE TITLE
Ghostscript python library 

### ISSUE THREAD

**Issue by arian81** [theeko74/pdfc#7]
It's just an idea, but wouldn't it be easier if the Ghostscript python library was used instead of converting it to terminal commands and using the Ghostscript binary

**Comment by theeko74** [comment]
Hi, yes I think that's a good idea that could solve compatibility issue with Windows.
I did not know that there was a Ghostscript python lib. Thanks

**Comment by theeko74** [comment]
OK, I've looked this idea:
The nice idea by using Ghostscript python lib was for the installation where user can do "pip install ghostscript" and that will be done... The problem is that ghostscript lib depends on the installation of ghostscript bin manually so it is not very much interesting...
